server:
  port: 0

spring:
  data:
    mongodb:
      username: test
      password: passwordvalue
      uri: mongodb://localhost:27017/paquetes_internet
  application:
    name: paquetesinternet

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka